package plataforma;
import paraProyectoClase.Bolsas.*;
import javax.swing.JOptionPane;


/**
 *
 * @author DANIELCASTELAO\mmartinezcosta
 */
public class Principal extends javax.swing.JFrame {
     
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    this.setResizable(false);
    this.setSize(1280,720);
    this.setLocationRelativeTo(null);
    
        Carne.setVisible(false);
        Pescado.setVisible(false);
        Ensalada.setVisible(false);
        Seleccion.setVisible(false);
        TipoBolsa.setVisible(false);
        SeleccionBebida.setVisible(false);
        Salir.setVisible(true);
    
        Agua.setVisible(false);
        Refresco.setVisible(false);
        Cerveza.setVisible(false);
        
        BolsaPlastica.setVisible(false);
        BolsaPapel.setVisible(false);
            
        BolsaPlastica.setEnabled(false);
        BolsaPapel.setEnabled(false);
    }
    
    public void Pedido() {
                 
        ComerAquí.setEnabled(true);
        ADomicilio.setEnabled(true);
        Salir.setEnabled(true);
        TipoBolsa.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        ADomicilio = new javax.swing.JButton();
        ComerAquí = new javax.swing.JButton();
        Carne = new javax.swing.JButton();
        Pescado = new javax.swing.JButton();
        Ensalada = new javax.swing.JButton();
        Salir = new javax.swing.JButton();
        Seleccion = new javax.swing.JLabel();
        Agua = new javax.swing.JButton();
        Refresco = new javax.swing.JButton();
        Cerveza = new javax.swing.JButton();
        BolsaPlastica = new javax.swing.JButton();
        BolsaPapel = new javax.swing.JButton();
        TipoBolsa = new javax.swing.JLabel();
        SeleccionBebida = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1280, 720));

        jPanel1.setBackground(new java.awt.Color(187, 127, 66));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ADomicilio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/A domicilio.jpg"))); // NOI18N
        ADomicilio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ADomicilioActionPerformed(evt);
            }
        });
        jPanel1.add(ADomicilio, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 160, -1, -1));

        ComerAquí.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Comer aqui.png"))); // NOI18N
        ComerAquí.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComerAquíActionPerformed(evt);
            }
        });
        jPanel1.add(ComerAquí, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        Carne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Carne.jpg"))); // NOI18N
        Carne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarneActionPerformed(evt);
            }
        });
        jPanel1.add(Carne, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        Pescado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Pescado.jpg"))); // NOI18N
        Pescado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PescadoActionPerformed(evt);
            }
        });
        jPanel1.add(Pescado, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        Ensalada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Ensalada.jpg"))); // NOI18N
        Ensalada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EnsaladaActionPerformed(evt);
            }
        });
        jPanel1.add(Ensalada, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, -1, -1));

        Salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Salir.jpg"))); // NOI18N
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, -1, 90));

        Seleccion.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        Seleccion.setForeground(new java.awt.Color(116, 50, 12));
        Seleccion.setText("Seleccione su plato");
        jPanel1.add(Seleccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        Agua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Agua.jpg"))); // NOI18N
        Agua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AguaActionPerformed(evt);
            }
        });
        jPanel1.add(Agua, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        Refresco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Refresco.png"))); // NOI18N
        Refresco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefrescoActionPerformed(evt);
            }
        });
        jPanel1.add(Refresco, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, -1, -1));

        Cerveza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Cerveza.jpg"))); // NOI18N
        Cerveza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CervezaActionPerformed(evt);
            }
        });
        jPanel1.add(Cerveza, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 230, -1, -1));

        BolsaPlastica.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Plastica.jpg"))); // NOI18N
        BolsaPlastica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolsaPlasticaActionPerformed(evt);
            }
        });
        jPanel1.add(BolsaPlastica, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        BolsaPapel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Papel.jpg"))); // NOI18N
        BolsaPapel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BolsaPapelActionPerformed(evt);
            }
        });
        jPanel1.add(BolsaPapel, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        TipoBolsa.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        TipoBolsa.setForeground(new java.awt.Color(116, 50, 12));
        TipoBolsa.setText("Seleccione su tipo de bolsa");
        jPanel1.add(TipoBolsa, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, -1, -1));

        SeleccionBebida.setFont(new java.awt.Font("DialogInput", 0, 24)); // NOI18N
        SeleccionBebida.setForeground(new java.awt.Color(116, 50, 12));
        SeleccionBebida.setText("Seleccione su bebida");
        jPanel1.add(SeleccionBebida, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 150, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ComerAquíActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComerAquíActionPerformed
        // TODO add your handling code here:
        Salir.setVisible(true);  
        Salir.setEnabled(true);        
        TipoBolsa.setVisible(false);    
        
            ComerAquí.setEnabled(false);
            ADomicilio.setEnabled(false);
            
            ComerAquí.setVisible(false);
            ADomicilio.setVisible(false);
            
            Seleccion.setVisible(true);
            
            Carne.setVisible(true);
            Pescado.setVisible(true);
            Ensalada.setVisible(true);
            
            Carne.setEnabled(true);
            Pescado.setEnabled(true);
            Ensalada.setEnabled(true);
            
            
               
    }//GEN-LAST:event_ComerAquíActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Su pedido ha sido cancelado");
        
        System.exit(0);
                
    }//GEN-LAST:event_SalirActionPerformed

    private void CarneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarneActionPerformed
        // TODO add your handling code here:
            TipoBolsa.setVisible(false);
        
            Carne.setVisible(false);
            Pescado.setVisible(false);
            Ensalada.setVisible(false);
            
            Carne.setEnabled(false);
            Pescado.setEnabled(false);
            Ensalada.setEnabled(false);
        
        Agua.setVisible(true);
        Refresco.setVisible(true);
        Cerveza.setVisible(true);
        
        Agua.setEnabled(true);
        Refresco.setEnabled(true);
        Cerveza.setEnabled(true);
        
            JOptionPane.showMessageDialog(null,"Su pedido de Carne se ha comenzado a preparar");

            Seleccion.setVisible(false);
            SeleccionBebida.setVisible(true);
    }//GEN-LAST:event_CarneActionPerformed

    private void PescadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PescadoActionPerformed
        // TODO add your handling code here:
            TipoBolsa.setVisible(false);
        
            Carne.setVisible(false);
            Pescado.setVisible(false);
            Ensalada.setVisible(false);
            
            Carne.setEnabled(false);
            Pescado.setEnabled(false);
            Ensalada.setEnabled(false);
            
        Agua.setVisible(true);
        Refresco.setVisible(true);
        Cerveza.setVisible(true);
        
        Agua.setEnabled(true);
        Refresco.setEnabled(true);
        Cerveza.setEnabled(true);
        
            JOptionPane.showMessageDialog(null,"Su pedido de Pescado se ha comenzado a preparar");
        
            Seleccion.setVisible(false);
            SeleccionBebida.setVisible(true);
    }//GEN-LAST:event_PescadoActionPerformed

    private void EnsaladaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnsaladaActionPerformed
        // TODO add your handling code here:
            TipoBolsa.setVisible(false);
        
            Carne.setVisible(false);
            Pescado.setVisible(false);
            Ensalada.setVisible(false);
            
            Carne.setEnabled(false);
            Pescado.setEnabled(false);
            Ensalada.setEnabled(false);
            
        Agua.setVisible(true);
        Refresco.setVisible(true);
        Cerveza.setVisible(true);
        
        Agua.setEnabled(true);
        Refresco.setEnabled(true);
        Cerveza.setEnabled(true);
        
            JOptionPane.showMessageDialog(null,"Su pedido de Ensalada se ha comenzado a preparar");
        
            Seleccion.setVisible(false);
            SeleccionBebida.setVisible(true);
    }//GEN-LAST:event_EnsaladaActionPerformed

    private void AguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AguaActionPerformed
        // TODO add your handling code here:
            TipoBolsa.setVisible(false);
        
            Carne.setVisible(false);
            Pescado.setVisible(false);
            Ensalada.setVisible(false);
            
            Carne.setEnabled(false);
            Pescado.setEnabled(false);
            Ensalada.setEnabled(false);
        
        JOptionPane.showMessageDialog(null,"En breves traerán su agua");
        System.exit(0);
    }//GEN-LAST:event_AguaActionPerformed

    private void RefrescoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefrescoActionPerformed
        // TODO add your handling code here:
            TipoBolsa.setVisible(false);
        
            Carne.setVisible(false);
            Pescado.setVisible(false);
            Ensalada.setVisible(false);
            
            Carne.setEnabled(false);
            Pescado.setEnabled(false);
            Ensalada.setEnabled(false);
            
        JOptionPane.showMessageDialog(null,"En breves traerán su refresco");
        System.exit(0);
    }//GEN-LAST:event_RefrescoActionPerformed

    private void CervezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CervezaActionPerformed
        // TODO add your handling code here:
            TipoBolsa.setVisible(false);
        
            Carne.setVisible(false);
            Pescado.setVisible(false);
            Ensalada.setVisible(false);
            
            Carne.setEnabled(false);
            Pescado.setEnabled(false);
            Ensalada.setEnabled(false);
            
        JOptionPane.showMessageDialog(null, "En breves traerán su cerveza");
        System.exit(0);
    }//GEN-LAST:event_CervezaActionPerformed

    private void ADomicilioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ADomicilioActionPerformed
        // TODO add your handling code here:
        
        Salir.setVisible(true);  
        Salir.setEnabled(true);        
        
        TipoBolsa.setVisible(true);
        
            ComerAquí.setEnabled(false);
            ADomicilio.setEnabled(false);
            
            ComerAquí.setVisible(false);
            ADomicilio.setVisible(false);
            
            Seleccion.setVisible(false);
            
            Carne.setVisible(false);
            Pescado.setVisible(false);
            Ensalada.setVisible(false);
            
            Carne.setEnabled(false);
            Pescado.setEnabled(false);
            Ensalada.setEnabled(false);
            
            BolsaPlastica.setVisible(true);
            BolsaPapel.setVisible(true);
            
            BolsaPlastica.setEnabled(true);
            BolsaPapel.setEnabled(true);
                        
    }//GEN-LAST:event_ADomicilioActionPerformed

    private void BolsaPlasticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolsaPlasticaActionPerformed
        // TODO add your handling code here:
        paraProyectoClase.Bolsas.BolsaPlastica();
                
        Carne.setVisible(true);
            Pescado.setVisible(true);
            Ensalada.setVisible(true);
            
            Carne.setEnabled(true);
            Pescado.setEnabled(true);
            Ensalada.setEnabled(true);
            
            BolsaPlastica.setVisible(false);
            BolsaPapel.setVisible(false);
            
        BolsaPlastica.setEnabled(false);
        BolsaPapel.setEnabled(false);
        
        Seleccion.setVisible(true);
        TipoBolsa.setVisible(false);
    }//GEN-LAST:event_BolsaPlasticaActionPerformed

    private void BolsaPapelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BolsaPapelActionPerformed
        // TODO add your handling code here:
        paraProyectoClase.Bolsas.BolsaPapel();
        
            Carne.setVisible(true);
            Pescado.setVisible(true);
            Ensalada.setVisible(true);
            
            Carne.setEnabled(true);
            Pescado.setEnabled(true);
            Ensalada.setEnabled(true);
            
            BolsaPlastica.setVisible(false);
            BolsaPapel.setVisible(false);
            
        BolsaPlastica.setEnabled(false);
        BolsaPapel.setEnabled(false);
        
        Seleccion.setVisible(true);
        TipoBolsa.setVisible(false);
    }//GEN-LAST:event_BolsaPapelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ADomicilio;
    private javax.swing.JButton Agua;
    private javax.swing.JButton BolsaPapel;
    private javax.swing.JButton BolsaPlastica;
    private javax.swing.JButton Carne;
    private javax.swing.JButton Cerveza;
    private javax.swing.JButton ComerAquí;
    private javax.swing.JButton Ensalada;
    private javax.swing.JButton Pescado;
    private javax.swing.JButton Refresco;
    private javax.swing.JButton Salir;
    private javax.swing.JLabel Seleccion;
    private javax.swing.JLabel SeleccionBebida;
    private javax.swing.JLabel TipoBolsa;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}